---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-10:
    <<: *test
    docker:
      - image: node:10
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - run: .circleci/release

workflows:
  version: 2
  "eslint-config-oclif":
    jobs:
      - node-latest
      - node-12
      - node-10
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-12
            - node-10
